### ISSUE TITLE
[Suggestion] Add support for repeating via `.`

### ISSUE THREAD

**Issue by rnevius** [flwyd/vim-conjoin#2]
As above. It would be great to have support for repeating conjoin function calls via `.`. An easy way to do this would be to hook into [vim-repeat](https://github.com/tpope/vim-repeat)'s `repeat#set()` function.

**Comment by rnevius** [comment]
Closing this, as I completely misunderstood what this plugin was doing. 😅

**Comment by flwyd** [comment]
Thanks for bringing this up.  I hadn't thought to test repeating via `.` and it's definitely unsatisfactory, even when the previous join didn't affect any continuation lines.  Will fix it soon.
